let dataV={"nodes": [{"name": "HDPE"}, {"name": "LDPE"}, {"name": "PP"}, {"name": "PLA"}, {"name": "PHA"}, {"name": "Households"}, {"name": "Curbside Collection"}, {"name": "Dropoff"}, {"name": "Incineration"}, {"name": "Landfill"}, {"name": "Pyrolysis"}, {"name": "Segregation"}, {"name": "Losses"}, {"name": "rHDPE"}, {"name": "rLDPE"}, {"name": "rPP"}, {"name": "rPLA"}, {"name": "rPHA"}, {"name": "Compost"}],
"links": 

[{"source": "HDPE", "target": "Households", "value": 2.69, "optimal": "yes"},
{"source": "LDPE", "target": "Households", "value": 0, "optimal": "yes"},
{"source": "PP", "target": "Households", "value": 0.0, "optimal": "yes"},
{"source": "PLA", "target": "Households", "value": 0.0, "optimal": "yes"},
{"source": "PHA", "target": "Households", "value": 0.0, "optimal": "yes"},
{"source": "Households", "target": "Curbside Collection", "value": 2.37, "optimal": "yes"},
{"source": "Households", "target": "Dropoff", "value": 0.0, "optimal": "yes"},
{"source": "Households", "target": "Losses", "value": 0.319, "optimal": "yes"},
{"source": "Curbside Collection", "target": "Incineration", "value": 0, "optimal": "yes"},
{"source": "Dropoff", "target": "Incineration", "value": 0.0, "optimal": "yes"},
{"source": "Curbside Collection", "target": "Landfill", "value": 0, "optimal": "yes"},
{"source": "Dropoff", "target": "Landfill", "value": 0.0, "optimal": "yes"},
{"source": "Curbside Collection", "target": "Pyrolysis", "value": 0.0, "optimal": "yes"},
{"source": "Dropoff", "target": "Pyrolysis", "value": 0.0, "optimal": "yes"},
{"source": "Curbside Collection", "target": "Segregation", "value": 2.16, "optimal": "yes"},
{"source": "Dropoff", "target": "Segregation", "value": 0.0, "optimal": "yes"},
{"source": "Curbside Collection", "target": "Losses", "value": 0.19, "optimal": "yes"},
{"source": "Dropoff", "target": "Losses", "value": 0.0, "optimal": "yes"},
{"source": "Incineration", "target": "Losses", "value": 0.05, "optimal": "yes"},
{"source": "Incineration", "target": "Landfill", "value": 0.09, "optimal": "yes"},
{"source": "Landfill", "target": "Losses", "value": 0, "optimal": "yes"},
{"source": "Pyrolysis", "target": "Losses", "value": 0.0, "optimal": "yes"},
{"source": "Segregation", "target": "Losses", "value": 0.38, "optimal": "yes"},
{"source": "Segregation", "target": "Incineration", "value": 0.79, "optimal": "yes"},
{"source": "Segregation", "target": "rHDPE", "value": 1.78, "optimal": "yes"},
{"source": "Segregation", "target": "rLDPE", "value": 0, "optimal": "yes"},
{"source": "Segregation", "target": "rPP", "value": 0.0, "optimal": "yes"},
{"source": "Segregation", "target": "rPLA", "value": 0.0, "optimal": "yes"},
{"source": "Segregation", "target": "rPHA", "value": 0.0, "optimal": "yes"},
{"source": "Segregation", "target": "Compost", "value": 0.0, "optimal": "yes"},
{"source": "rHDPE", "target": "Losses", "value": 0.16, "optimal": "yes"},
{"source": "rLDPE", "target": "Losses", "value": 0, "optimal": "yes"},
{"source": "rPP", "target": "Losses", "value": 0.0, "optimal": "yes"},
{"source": "rPLA", "target": "Losses", "value": 0.0, "optimal": "yes"},
{"source": "rPHA", "target": "Losses", "value": 0.0, "optimal": "yes"},
{"source": "Compost", "target": "Losses", "value": 0, "optimal": "yes"},
     {"source": "rHDPE", "target": "HDPE", "value": 0.977, "optimal": "yes"},
     {"source": "rLDPE", "target": "LDPE", "value": 0, "optimal": "yes"},
     {"source": "rPP", "target": "PP", "value": 0.0, "optimal": "yes"},
     {"source": "rPLA", "target": "PLA", "value": 0.0, "optimal": "yes"},
     {"source": "rPHA", "target": "PHA", "value": 0.0, "optimal": "yes"}
]};
